module.exports = ActionType = {
  'LANDING_TOGGLE_SUCCESS'
  'REPOSITORY_SELECT_SUCCESS'
  'ORGANIZATION_SELECT_SUCCESS'
  'SHOW_LOADER_TOGGLE_SUCCESS'
  USER_AUTHENTICATION_WITH_CREDENTIAL :
    START   : 'USER_AUTHENTICATION_WITH_CREDENTIAL_START'
    SUCCESS : 'USER_AUTHENTICATION_WITH_CREDENTIAL_SUCCESS'
    FAILURE : 'USER_AUTHENTICATION_WITH_CREDENTIAL_FAILURE'
  USER_AUTHENTICATION :
    SUCCESS : 'USER_AUTHENTICATION_SUCCESS'
    FAILURE : 'USER_AUTHENTICATION_FAILURE'
  AUTHENTICATION :
    SUCCESS : 'AUTHENTICATION_SUCCESS'
    FAILURE : 'AUTHENTICATION_FAILURE'
  SIGN_OUT :
    SUCCESS : 'SIGN_OUT_SUCCESS'
    FAILURE : 'SIGN_OUT_FAILURE'
  FETCH_ORGANIZATIONS :
    START   : 'FETCH_ORGANIZATIONS_START'
    SUCCESS : 'FETCH_ORGANIZATIONS_SUCCESS'
    FAILURE : 'FETCH_ORGANIZATIONS_FAILURE'
  FETCH_MY_ROLE_IN_ORGANIZATION :
    START   : 'FETCH_MY_ROLE_IN_ORGANIZATION_START'
    SUCCESS : 'FETCH_MY_ROLE_IN_ORGANIZATION_SUCCESS'
    FAILURE : 'FETCH_MY_ROLE_IN_ORGANIZATION_FAILURE'
  FETCH_ORGANIZATION_OWNERS :
    START   : 'FETCH_ORGANIZATION_OWNERS_START'
    SUCCESS : 'FETCH_ORGANIZATION_OWNERS_SUCCESS'
    FAILURE : 'FETCH_ORGANIZATION_OWNERS_FAILURE'
  FETCH_REPOSITORIES :
    START   : 'FETCH_REPOSITORIES_START'
    SUCCESS : 'FETCH_REPOSITORIES_SUCCESS'
    FAILURE : 'FETCH_REPOSITORIES_FAILURE'
  SELECTED_REPOSITORIES :
    START   : 'SELECTED_REPOSITORIES_START'
    SUCCESS : 'SELECTED_REPOSITORIES_SUCCESS'
    FAILURE : 'SELECTED_REPOSITORIES_FAILURE'
  REPOSITORY_SETUP :
    START   : 'REPOSITORY_SETUP_START'
    SUCCESS : 'REPOSITORY_SETUP_SUCCESS'
    FAILURE : 'REPOSITORY_SETUP_FAILURE'
  KODING_SIGN_IN :
    START   : 'KODING_SIGN_IN_START'
    SUCCESS : 'KODING_SIGN_IN_SUCCESS'
    FAILURE : 'KODING_SIGN_IN_FAILURE'
  CREATE_STACK_TEMPLATE :
    START   : 'CREATE_STACK_TEMPLATE_START'
    SUCCESS : 'CREATE_STACK_TEMPLATE_SUCCESS'
    FAILURE : 'CREATE_STACK_TEMPLATE_FAILURE'
}
